[general]
time-step = 1 # Float in days

[population]
size = 1000000 # How many people are in the entire graph
uniformity = 0.9 # How equally spread are the parameters
age-groups = [30, 40, 50, 60, 70, 80] # What are the intervall borders of age groups

[population.behaviour]
# Parameters for behaviour like handshakes, hugging, ...

[population.public-spaces]
# Parameters for public spaces like concerts, theaters, pubs, ...

[virus]
# What is the likelihood of an infection when 'encountering' an infected individual
contagiousness = 0.5
# Number of days an infected individual may infect others
contagious_for = 14
# How likely is a person in each of the intervalls to die, if infected
lethality = [0.0, 0.01, 0.02, 0.03, 0.1, 0.2, 0.3] 
