save_to_file = true

[population]
size = 20000000
age_distribution = [0.08, 0.09, 0.1, 0.1, 0.13, 0.2, 0.1, 0.1, 0.08, 0.02]
household_size = 10
district_size = 2000
city_size = 2000000
mean_household_mobility = 0.4 # Mean probability of an infectious encounter with a member of the same household
mean_district_mobility = 0.01 # Mean probability of an infectious encounter with a member of the same district, but not the same household
mean_city_mobility = 0.005 # Mean probability of an infectious encounter with a member of the same city, but not the same district
mean_national_mobility = 0.002 # Mean probability of an infectious encounter with a memeber of the same society, but not the same city
city_medical_capacity = 1000

# The probabilities may be influenced by isolation, hygiene, ...
[virus]
contagiousness = 1
contagious_for = 14
sick_for = 14
lethality = [
    0.002,
    0.002,
    0.002,
    0.004,
    0.013,
    0.036,
    0.08,
    0.148,
    0.148,
    0.148,
]
# The treatment factor t gets multiplied with the lethality.
# $$ t = 1-\text{efficiency}*(1-\text{decay})^{-delay}$$
# where delay is the time the person was infected but not in treatment.
treatment_decay = 0.3
treatment_efficiency = 0.7
# How much less likely is it that someone in quarantine is going to infect someone
# else?
treatment_quarantine_efficiency = 0.9
